POST https://booking-app.test/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "watilyji@mailinator.com",
    "password": "password"
}

###
GET https://booking-app.test/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer IgXsV62lR7ZZwe2ZGWZrJMqpgZs1FFId4XJOblJpea54809a

###
GET https://booking-app.test/api/appointments/generate-magic-link?user=watilyji@mailinator.com
Accept: application/json
Content-Type: application/json
Authorization: Bearer IgXsV62lR7ZZwe2ZGWZrJMqpgZs1FFId4XJOblJpea54809a

###

